purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3028674
  brandStrength: 0.625
  lightness: 0.3512545
  brandColors:
    - '#0e0e0e'
    - '#ffffff'
    - '#7e6b5c'
    - '#b2d2f8'
    - '#524847'
  rhythmicContrast: 0.797491
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Michael Gotzen
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4946237
layout_spectrum: 0.5358423
