name: Michael Gotzen
favicon: null
layout_spectrum: 0.26058402843773365
typography_spectrum: 0.5159390547778457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6647551651112735
  lightness: 0.10499001806601882
  saturation: 0.49345869524404407
  rhythmicContrast: 0.9138439702801406
purpose: []
